[package]
name = "payroll_impact_analysis_tool"
version = "0.1.0"
authors = ["Yoann Katchourine <yoann.katchourine@globepayroll.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
